name: Loki
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch'
        required: true
        default: 'master'
      os:
        description: 'Target os, ios/android/both'
        required: false
        default: 'both'
      group:
        description: 'Group to be distributed to'
        required: true
        default: 'gree'

env: 
  GITHUB_CONTEXT: ${{ toJSON(github) }}

jobs:
  # Common flutter pub setup
  flutter-config:
    name: Flutter Config
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Dumping Repo Info
        run: echo "$GITHUB_CONTEXT"

  # Build Job for Android
  android-build:
    if: ${{ env.os == 'android' || env.os == 'both' }}
    name: Android Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      # Setup the flutter environment.
      - name: Calling subosito/flutter action
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' 

      # Get flutter dependencies and build apk
      - name: Pub get and build apk
        run: |
          flutter pub get
          flutter build apk

      # Upload generated apk to the artifacts.
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
          retention-days: 14

      # Distribute the apk using Firebase
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with: 
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          file: build/app/outputs/apk/release/app-release.apk
  
  # Build Job for iOS
  ios-build:
    if: ${{ env.os == 'iOS' || env.os == 'both' }}
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Dumping Repo Info
        run: echo "$GITHUB_CONTEXT"
      
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      # Setup the flutter environment.
      - name: Calling subosito/flutter action
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Use Xcode 12.4
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'

      # Get flutter dependencies and build ipa
      - name: Pub get and build ipa
        run: |
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign     

      # Upload     
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: build/ios/iphoneos
          retention-days: 14
